controller_list:
  - name: fake_arduinobot_controller
    joints:
      - base_link_to_plate
      - base_support_to_forward_drive_arm
      - forward_drive_arm_to_horizontal_arm
  - name: fake_gripper_controller
    joints:
      - claw_support_to_left_finger
      - claw_support_to_right_finger